stages:
  - build
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

build:
  stage: build
  script:
    - echo "Building the application..."
    - composer install --no-dev --prefer-dist --optimize-autoloader
    - npm install && npm run prod
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
  artifacts:
    paths:
      - .env
      - vendor/
      - public/
      - resources/views/
      - routes/
      - bootstrap/
      - storage/
      - app/

deploy:
  stage: deploy
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "mkdir -p /public_html/crudlaravel/"
    - sshpass -p "$SSH_PASSWORD" rsync -avz --delete --exclude='.git/' --exclude='storage/logs/' --exclude='.env' -e "ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/public_html/crudlaravel/
  only:
    - main
